import { createContext, useContext, useState } from 'react';

const RoomsContext = createContext(null);
const cardData = [
  {
    id: 1,
    imageUrl: '/1room.svg',
    roomName: 'Ocean Meeting Room',
    address: 'Lviv, Shevchenka St., Ukraine, Floor 1',
    peoples: '4-12',
    rating: '4.7',
    price: '12',
    status: 'Available',
    isBooked: false,
    isLiked: false,
    description: 'This room has a wide ocean view. It is designed for productive meetings. Natural light fills the space throughout the day. The atmosphere is calm and focused.',
    bookingsCount: 24,
    squareMeters: 45,
    projector: true,
    soundSystem: true,
    wifi: true,
    powerSocket: true,
    jacuzzi: false,
    cleaningService: true,
    bedCoffee: false,
  },
  {
    id: 2,
    imageUrl: '/2room.svg',
    roomName: 'Skyline Meeting Room',
    address: 'Lviv, Shevchenka St., Ukraine, Floor 2',
    peoples: '2-4',
    rating: '4.8',
    price: '10',
    status: 'Available',
    isBooked: false,
    isLiked: false,
    description: 'This room offers a panoramic city skyline view. It is suitable for small team discussions. The space is quiet and minimalistic. It supports focused work sessions.',
    bookingsCount: 18,
    squareMeters: 30,
    projector: true,
    soundSystem: false,
    wifi: true,
    powerSocket: true,
    jacuzzi: false,
    cleaningService: true,
    bedCoffee: false,
  },
  {
    id: 3,
    imageUrl: '/3room.svg',
    roomName: 'Berlin Conference Room',
    address: 'Lviv, Shevchenka St., Ukraine, Floor 1',
    peoples: '12+',
    rating: '4.3',
    price: '16',
    status: 'Available',
    isBooked: false,
    isLiked: false,
    description: 'This room is built for large meetings. It has a formal business setup. The space includes modern equipment. It is ideal for presentations and conferences.',
    bookingsCount: 11,
    squareMeters: 70,
    projector: true,
    soundSystem: true,
    wifi: true,
    powerSocket: true,
    jacuzzi: false,
    cleaningService: true,
    bedCoffee: false,
  },
  {
    id: 4,
    imageUrl: '/4room.svg',
    roomName: 'Minimal Work Room',
    address: 'Lviv, Shevchenka St., Ukraine, Floor 2',
    peoples: '2-4',
    rating: '4.6',
    price: '9',
    status: 'Available',
    isBooked: false,
    isLiked: false,
    description: 'This room is designed for deep focus. It has a simple and clean layout. Distractions are minimized. It is perfect for individual or small tasks.',
    bookingsCount: 33,
    squareMeters: 22,
    projector: false,
    soundSystem: false,
    wifi: true,
    powerSocket: true,
    jacuzzi: false,
    cleaningService: true,
    bedCoffee: false,
  },
  {
    id: 5,
    imageUrl: '/5room.svg',
    roomName: 'Creative Studio Room',
    address: 'Lviv, Shevchenka St., Ukraine, Floor 3',
    peoples: '4-12',
    rating: '4.9',
    price: '14',
    status: 'Available',
    isBooked: false,
    isLiked: false,
    description: 'This room is designed for creative teams. It supports brainstorming sessions. The layout is flexible and modern. It inspires collaboration and ideas.',
    bookingsCount: 40,
    squareMeters: 50,
    projector: true,
    soundSystem: true,
    wifi: true,
    powerSocket: true,
    jacuzzi: false,
    cleaningService: true,
    bedCoffee: false,
  },
  {
    id: 6,
    imageUrl: '/6room.svg',
    roomName: 'Executive Room',
    address: 'Lviv, Shevchenka St., Ukraine, Floor 4',
    peoples: '4-12',
    rating: '4.5',
    price: '18',
    status: 'Available',
    isBooked: false,
    isLiked: false,
    description: 'This room is built for executive meetings. It has a premium interior design. The space is quiet and professional. It supports important decision making.',
    bookingsCount: 15,
    squareMeters: 60,
    projector: true,
    soundSystem: true,
    wifi: true,
    powerSocket: true,
    jacuzzi: false,
    cleaningService: true,
    bedCoffee: false,
  },
  {
    id: 7,
    imageUrl: '/7room.svg',
    roomName: 'Startup Hub Room',
    address: 'Lviv, Shevchenka St., Ukraine, Floor 2',
    peoples: '2-4',
    rating: '4.4',
    price: '11',
    status: 'Available',
    isBooked: false,
    isLiked: false,
    description: 'This room is designed for startup teams. It encourages collaboration and fast thinking. The environment is flexible and modern. It supports daily standups and planning.',
    bookingsCount: 27,
    squareMeters: 35,
    projector: true,
    soundSystem: false,
    wifi: true,
    powerSocket: true,
    jacuzzi: false,
    cleaningService: true,
    bedCoffee: false,
  },
  {
    id: 8,
    imageUrl: '/8room.svg',
    roomName: 'Luxury Lounge Room',
    address: 'Lviv, Shevchenka St., Ukraine, Floor 5',
    peoples: '4-12',
    rating: '4.8',
    price: '20',
    status: 'Available',
    isBooked: false,
    isLiked: false,
    description: 'This room has a luxury lounge design. It is comfortable and spacious. The interior is premium and elegant. It is suitable for high-end meetings.',
    bookingsCount: 9,
    squareMeters: 80,
    projector: true,
    soundSystem: true,
    wifi: true,
    powerSocket: true,
    jacuzzi: true,
    cleaningService: true,
    bedCoffee: true,
  },
  {
    id: 9,
    imageUrl: '/9room.svg',
    roomName: 'Cozy Small Room',
    address: 'Lviv, Shevchenka St., Ukraine, Floor 1',
    peoples: '2-4',
    rating: '4.2',
    price: '7',
    status: 'Available',
    isBooked: false,
    isLiked: false,
    description: 'This room is small and cozy. It is suitable for private calls. The environment is quiet and simple. It helps to stay concentrated.',
    bookingsCount: 52,
    squareMeters: 18,
    projector: false,
    soundSystem: false,
    wifi: true,
    powerSocket: true,
    jacuzzi: false,
    cleaningService: true,
    bedCoffee: false,
  },
  {
    id: 10,
    imageUrl: '/10room.svg',
    roomName: 'Innovation Lab Room',
    address: 'Lviv, Shevchenka St., Ukraine, Floor 3',
    peoples: '12+',
    rating: '4.9',
    price: '19',
    status: 'Available',
    isBooked: false,
    isLiked: false,
    description: 'This room is designed for innovation and experiments. It supports technical workshops. The environment is modern and flexible. It is ideal for prototyping ideas.',
    bookingsCount: 21,
    squareMeters: 75,
    projector: true,
    soundSystem: true,
    wifi: true,
    powerSocket: true,
    jacuzzi: false,
    cleaningService: true,
    bedCoffee: false,
  },
];
export function RoomsProvider({ children }) {
  const [rooms, setRooms] = useState(cardData);



  return (
    <RoomsContext.Provider value={{ rooms }}>{children}</RoomsContext.Provider>
  );
}

export function useRooms() {
  return useContext(RoomsContext);
}
